name: update-database
on:
  schedule:
    - cron: "0 00 1 * *"
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - name: Check out repo
      - uses: actions/checkout@v3
      
      - name: Set up Node && Clean install dependencies && Run update script
      - uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: | 
          npm ci
          npm run update
