name: update-database

on:
  schedule:
    - cron: "0 00 1 * *"
  workflow_dispatch:

jobs:
  update-database-local-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Clean install dependencies
        run: npm ci
      - name: Run update script
        run: npm run update

  update-database-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - name: Set MONGO_URI environment variable
        run: echo "MONGO_URI=$MONGO_URI" >> $GITHUB_ENV
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
      - name: Clean install dependencies
        run: npm ci
      - name: Run update script
        run: npm run update
    if: env.MONGO_URI
