name: update-database
on:
  schedule:
    - cron: "0 00 1 * *"
  workflow_dispatch:

jobs:
  update-database-local-dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Clean install dependencies
        run: npm ci

      - name: Run update script
        run: npm run update

  update-database-production:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{secrets.MONGO_URI}}

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      
      - name: Clean install dependencies
        run: npm ci

      - name: Run update script
      - if: ${{ env.MONGO_URI != '' }}
        run: npm run update

