name: update-database
on:
  schedule:
    - cron: "0 00 1 * *"

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: cd backend
      - run: npm ci
      - run: npm run update
